### ISSUE TITLE
코딩 컨벤션을 지켜주세요

### ISSUE THREAD

**Issue by clucle** [cha-jihwan/chat-server#1]
crash_if_false( nullptr != chatting_session ); 

crash_if_false(nullptr != chatting_user); 

에서 괄호 하나에는 space 가 들어가있고, 하나는 없습니다.

하나로 통일 부탁드립니다!

https://github.com/cha-jihwan/chat-server/blob/ce930375ef6287c14c325cbb93ec6acfdee31dce/contents/chat_server.cpp#L17-L33

**Comment by clucle** [comment]
namespace 의 괄호 정렬 부탁드립니다!

https://github.com/cha-jihwan/chat-server/blob/ce930375ef6287c14c325cbb93ec6acfdee31dce/contents/room.h#L4-L18

**Comment by cha-jihwan** [comment]
알려주셔서 감사합니다.
알려주신 부분은 고쳤어요. 
앞으로 사소한 부분에 더 신경쓰면서 작업하겠습니다.

**Comment by clucle** [comment]
이슈 클로즈합니다.
