### ISSUE TITLE
empty 함수에 true == empty() 를 사용하시는 이유가 있을까요??

### ISSUE THREAD

**Issue by clucle** [cha-jihwan/chat-server#2]
empty 자체에서 비어있는지 아닌지로

```
if (pool_container.empty()) 
```

사용 하는 것이 보기에 더 좋아보이는데, 사용하시는 이유가 있다면 댓글 달아주시면 감사하겠습니다!

https://github.com/cha-jihwan/chat-server/blob/ce930375ef6287c14c325cbb93ec6acfdee31dce/core/object_pool.hpp#L40-L43

**Comment by clucle** [comment]
덧붙여서, 현재 싱글 쓰레드에서 사용한다고 가정해서 사용 하신 것으로 보이는데,

allocate 실패시, type T 에 대해서 에러 메세지가 있으면 디버깅에 더 좋아보입니다.

또한 aloocate 실패시 vector 공간을 추가하고 로그를 남기는 것도 좋아보입니다.

**Comment by cha-jihwan** [comment]
넵. 말씀하신대로 의도는 싱글스레드에서 간단하게 쓰기 위해서 제작하였습니다.
일단 위에 vector의 empty()는 말씀해주신편이 가독성이 좋아보여서 변경하였습니다.

아래의 allocate() 실패시 type T에대한 로깅 방법은 좋은 방법을 찾아보고 추가하겠습니다.
질문이 가능하다면 마지막에 말씀해주신 vector 공간을 추가 시키는 이유가 있을까요?

**Comment by clucle** [comment]
vector 공간을 추가한다는 뜻은, 혹시나 공간이 부족할 경우에 추가적으로 object를 할당해주는건 어떨가 하는 의견이었습니다.

예를 들어 std::vector 의 push_back 에서 추가적으로 공간이 필요할 경우 capacity를 늘리는 것 처럼요.

싱글쓰레드이기 때문에, 구현 자체는 쉬울 것으로 보여 말씀드렸습니다.

제가 댓글에 단것처럼
실패시 에러메세지( 메모리 풀 부족 ) or 실패시 풀에 공간 추가후 로그( 메모리 풀을 다 사용해서 새로 할당 )

둘 중 원하는 방향으로 진행하시면 좋을 것 같습니다!

**Comment by clucle** [comment]
구두로 전달하여 이슈 클로즈합니다.
